/* ISO 14819-2, Table 2 (paragraph 3.1.3, pages 5-57) */

#define TMC_EVENTS 2048

const std::string tmc_event[TMC_EVENTS][2]={
	{"0",""},
	{"1","traffic problem"},
	{"2","queuing traffic (with average speeds Q). Danger of stationary traffic"},
	{"3",""},
	{"4",""},
	{"5",""},
	{"6",""},
	{"7",""},
	{"8",""},
	{"9",""},
	{"10",""},
	{"11","over-height warning system triggered"},
	{"12","(Q) accident(s), traffic being directed around accident area"},
	{"13",""},
	{"14",""},
	{"15",""},
	{"16","closed, rescue and recovery work in progress"},
	{"17",""},
	{"18",""},
	{"19",""},
	{"20","service area overcrowded, drive to another service area"},
	{"21",""},
	{"22","service area, fuel station closed"},
	{"23","service area, restaurant closed"},
	{"24","bridge closed"},
	{"25","tunnel closed"},
	{"26","bridge blocked"},
	{"27","tunnel blocked"},
	{"28","road closed intermittently"},
	{"29",""},
	{"30",""},
	{"31",""},
	{"32",""},
	{"33",""},
	{"34",""},
	{"35",""},
	{"36","fuel station reopened"},
	{"37","restaurant reopened"},
	{"38",""},
	{"39",""},
	{"40","smog alert ended"},
	{"41","(Q) overtaking lane(s) closed"},
	{"42","(Q) overtaking lane(s) blocked"},
	{"43",""},
	{"44",""},
	{"45",""},
	{"46",""},
	{"47",""},
	{"48",""},
	{"49",""},
	{"50",""},
	{"51","roadworks, (Q) overtaking lane(s) closed"},
	{"52","(Q sets of) roadworks on the hard shoulder"},
	{"53","(Q sets of) roadworks in the emergency lane"},
	{"54",""},
	{"55","traffic problem expected"},
	{"56","traffic congestion expected"},
	{"57","normal traffic expected"},
	{"58",""},
	{"59",""},
	{"60",""},
	{"61","(Q) object(s) on roadway {something that does not neccessarily block the road or part of it} "},
	{"62","(Q) burst pipe(s)"},
	{"63","(Q) object(s) on the road. Danger"},
	{"64","burst pipe. Danger"},
	{"65",""},
	{"66",""},
	{"67",""},
	{"68",""},
	{"69",""},
	{"70","traffic congestion, average speed of 10 km/h"},
	{"71","traffic congestion, average speed of 20 km/h"},
	{"72","traffic congestion, average speed of 30 km/h"},
	{"73","traffic congestion, average speed of 40 km/h"},
	{"74","traffic congestion, average speed of 50 km/h"},
	{"75","traffic congestion, average speed of 60 km/h"},
	{"76","traffic congestion, average speed of 70 km/h"},
	{"77",""},
	{"78",""},
	{"79",""},
	{"80",""},
	{"81",""},
	{"82",""},
	{"83",""},
	{"84",""},
	{"85",""},
	{"86",""},
	{"87",""},
	{"88",""},
	{"89",""},
	{"90",""},
	{"91","delays (Q) for cars"},
	{"92",""},
	{"93",""},
	{"94",""},
	{"95",""},
	{"96",""},
	{"97",""},
	{"98",""},
	{"99",""},
	{"100",""},
	{"101","stationary traffic"},
	{"102","stationary traffic for 1 km"},
	{"103","stationary traffic for 2 km"},
	{"104","stationary traffic for 4 km"},
	{"105","stationary traffic for 6 km"},
	{"106","stationary traffic for 10 km"},
	{"107","stationary traffic expected"},
	{"108","queuing traffic (with average speeds Q)"},
	{"109","queuing traffic for 1 km (with average speeds Q)"},
	{"110","queuing traffic for 2 km (with average speeds Q)"},
	{"111","queuing traffic for 4 km (with average speeds Q)"},
	{"112","queuing traffic for 6 km (with average speeds Q)"},
	{"113","queuing traffic for 10 km (with average speeds Q)"},
	{"114","queuing traffic expected"},
	{"115","slow traffic (with average speeds Q)"},
	{"116","slow traffic for 1 km (with average speeds Q)"},
	{"117","slow traffic for 2 km (with average speeds Q)"},
	{"118","slow traffic for 4 km (with average speeds Q)"},
	{"119","slow traffic for 6 km (with average speeds Q)"},
	{"120","slow traffic for 10 km (with average speeds Q)"},
	{"121","slow traffic expected"},
	{"122","heavy traffic (with average speeds Q)"},
	{"123","heavy traffic expected"},
	{"124","traffic flowing freely (with average speeds Q)"},
	{"125","traffic building up (with average speeds Q)"},
	{"126","no problems to report"},
	{"127","traffic congestion cleared"},
	{"128","message cancelled"},
	{"129","stationary traffic for 3 km"},
	{"130","danger of stationary traffic"},
	{"131","queuing traffic for 3 km (with average speeds Q)"},
	{"132","danger of queuing traffic (with average speeds Q)"},
	{"133","long queues (with average speeds Q)"},
	{"134","slow traffic for 3 km (with average speeds Q)"},
	{"135","traffic easing"},
	{"136","traffic congestion (with average speeds Q)"},
	{"137","traffic lighter than normal (with average speeds Q)"},
	{"138","queuing traffic (with average speeds Q). Approach with care"},
	{"139","queuing traffic around a bend in the road"},
	{"140","queuing traffic over the crest of a hill"},
	{"141","all accidents cleared, no problems to report"},
	{"142","traffic heavier than normal (with average speeds Q)"},
	{"143","traffic very much heavier than normal (with average speeds Q)"},
	{"144",""},
	{"145",""},
	{"146",""},
	{"147",""},
	{"148",""},
	{"149",""},
	{"150",""},
	{"151",""},
	{"152",""},
	{"153",""},
	{"154",""},
	{"155",""},
	{"156",""},
	{"157",""},
	{"158",""},
	{"159",""},
	{"160",""},
	{"161",""},
	{"162",""},
	{"163",""},
	{"164",""},
	{"165",""},
	{"166",""},
	{"167",""},
	{"168",""},
	{"169",""},
	{"170",""},
	{"171",""},
	{"172",""},
	{"173",""},
	{"174",""},
	{"175",""},
	{"176",""},
	{"177",""},
	{"178",""},
	{"179",""},
	{"180",""},
	{"181",""},
	{"182",""},
	{"183",""},
	{"184",""},
	{"185",""},
	{"186",""},
	{"187",""},
	{"188",""},
	{"189",""},
	{"190",""},
	{"191",""},
	{"192",""},
	{"193",""},
	{"194",""},
	{"195",""},
	{"196",""},
	{"197",""},
	{"198",""},
	{"199",""},
	{"200","multi vehicle pile up. Delays (Q)"},
	{"201","(Q) accident(s)"},
	{"202","(Q) serious accident(s)"},
	{"203","multi-vehicle accident (involving Q vehicles)"},
	{"204","accident involving (a/Q) heavy lorr(y/ies)"},
	{"205","(Q) accident(s) involving hazardous materials"},
	{"206","(Q) fuel spillage accident(s)"},
	{"207","(Q) chemical spillage accident(s)"},
	{"208","vehicles slowing to look at (Q) accident(s)"},
	{"209","(Q) accident(s) in the opposing lanes"},
	{"210","(Q) shed load(s)"},
	{"211","(Q) broken down vehicle(s)"},
	{"212","(Q) broken down heavy lorr(y/ies)"},
	{"213","(Q) vehicle fire(s)"},
	{"214","(Q) incident(s)"},
	{"215","(Q) accident(s). Stationary traffic"},
	{"216","(Q) accident(s). Stationary traffic for 1 km"},
	{"217","(Q) accident(s). Stationary traffic for 2 km"},
	{"218","(Q) accident(s). Stationary traffic for 4 km"},
	{"219","(Q) accident(s). Stationary traffic for 6 km"},
	{"220","(Q) accident(s). Stationary traffic for 10 km"},
	{"221","(Q) accident(s). Danger of stationary traffic"},
	{"222","(Q) accident(s). Queuing traffic"},
	{"223","(Q) accident(s). Queuing traffic for 1 km"},
	{"224","(Q) accident(s). Queuing traffic for 2 km"},
	{"225","(Q) accident(s). Queuing traffic for 4 km"},
	{"226","(Q) accident(s). Queuing traffic for 6 km"},
	{"227","(Q) accident(s). Queuing traffic for 10 km"},
	{"228","(Q) accident(s). Danger of queuing traffic"},
	{"229","(Q) accident(s). Slow traffic"},
	{"230","(Q) accident(s). Slow traffic for 1 km"},
	{"231","(Q) accident(s). Slow traffic for 2 km"},
	{"232","(Q) accident(s). Slow traffic for 4 km"},
	{"233","(Q) accident(s). Slow traffic for 6 km"},
	{"234","(Q) accident(s). Slow traffic for 10 km"},
	{"235","(Q) accident(s). Slow traffic expected"},
	{"236","(Q) accident(s). Heavy traffic"},
	{"237","(Q) accident(s). Heavy traffic expected"},
	{"238","(Q) accident(s). Traffic flowing freely"},
	{"239","(Q) accident(s). Traffic building up"},
	{"240","road closed due to (Q) accident(s)"},
	{"241","(Q) accident(s). Right lane blocked"},
	{"242","(Q) accident(s). Centre lane blocked"},
	{"243","(Q) accident(s). Left lane blocked"},
	{"244","(Q) accident(s). Hard shoulder blocked"},
	{"245","(Q) accident(s). Two lanes blocked"},
	{"246","(Q) accident(s). Three lanes blocked"},
	{"247","accident. Delays (Q)"},
	{"248","accident. Delays (Q) expected"},
	{"249","accident. Long delays (Q)"},
	{"250","vehicles slowing to look at (Q) accident(s). Stationary traffic"},
	{"251","vehicles slowing to look at (Q) accident(s). Stationary traffic for 1 km"},
	{"252","vehicles slowing to look at (Q) accident(s). Stationary traffic for 2 km"},
	{"253","vehicles slowing to look at (Q) accident(s). Stationary traffic for 4 km"},
	{"254","vehicles slowing to look at (Q) accident(s). Stationary traffic for 6 km"},
	{"255","vehicles slowing to look at (Q) accident(s). Stationary traffic for 10 km"},
	{"256","vehicles slowing to look at (Q) accident(s). Danger of stationary traffic"},
	{"257","vehicles slowing to look at (Q) accident(s). Queuing traffic"},
	{"258","vehicles slowing to look at (Q) accident(s). Queuing traffic for 1 km"},
	{"259","vehicles slowing to look at (Q) accident(s). Queuing traffic for 2 km"},
	{"260","vehicles slowing to look at (Q) accident(s). Queuing traffic for 4 km"},
	{"261","vehicles slowing to look at (Q) accident(s). Queuing traffic for 6 km"},
	{"262","vehicles slowing to look at (Q) accident(s). Queuing traffic for 10 km"},
	{"263","vehicles slowing to look at (Q) accident(s). Danger of queuing traffic"},
	{"264","vehicles slowing to look at (Q) accident(s). Slow traffic"},
	{"265","vehicles slowing to look at (Q) accident(s). Slow traffic for 1 km"},
	{"266","vehicles slowing to look at (Q) accident(s). Slow traffic for 2 km"},
	{"267","vehicles slowing to look at (Q) accident(s). Slow traffic for 4 km"},
	{"268","vehicles slowing to look at (Q) accident(s). Slow traffic for 6 km"},
	{"269","vehicles slowing to look at (Q) accident(s). Slow traffic for 10 km"},
	{"270","vehicles slowing to look at (Q) accident(s). Slow traffic expected"},
	{"271","vehicles slowing to look at (Q) accident(s). Heavy traffic"},
	{"272","vehicles slowing to look at (Q) accident(s). Heavy traffic expected"},
	{"273",""},
	{"274","vehicles slowing to look at (Q) accident(s). Traffic building up"},
	{"275","vehicles slowing to look at accident. Delays (Q)"},
	{"276","vehicles slowing to look at accident. Delays (Q) expected"},
	{"277","vehicles slowing to look at accident. Long delays (Q)"},
	{"278","(Q) shed load(s). Stationary traffic"},
	{"279","(Q) shed load(s). Stationary traffic for 1 km"},
	{"280","(Q) shed load(s). Stationary traffic for 2 km"},
	{"281","(Q) shed load(s). Stationary traffic for 4 km"},
	{"282","(Q) shed load(s). Stationary traffic for 6 km"},
	{"283","(Q) shed load(s). Stationary traffic for 10 km"},
	{"284","(Q) shed load(s). Danger of stationary traffic"},
	{"285","(Q) shed load(s). Queuing traffic"},
	{"286","(Q) shed load(s). Queuing traffic for 1 km"},
	{"287","(Q) shed load(s). Queuing traffic for 2 km"},
	{"288","(Q) shed load(s). Queuing traffic for 4 km"},
	{"289","(Q) shed load(s). Queuing traffic for 6 km"},
	{"290","(Q) shed load(s). Queuing traffic for 10 km"},
	{"291","(Q) shed load(s). Danger of queuing traffic"},
	{"292","(Q) shed load(s). Slow traffic"},
	{"293","(Q) shed load(s). Slow traffic for 1 km"},
	{"294","(Q) shed load(s). Slow traffic for 2 km"},
	{"295","(Q) shed load(s). Slow traffic for 4 km"},
	{"296","(Q) shed load(s). Slow traffic for 6 km"},
	{"297","(Q) shed load(s). Slow traffic for 10 km"},
	{"298","(Q) shed load(s). Slow traffic expected"},
	{"299","(Q) shed load(s). Heavy traffic"},
	{"300","(Q) shed load(s). Heavy traffic expected"},
	{"301","(Q) shed load(s). Traffic flowing freely"},
	{"302","(Q) shed load(s). Traffic building up"},
	{"303","blocked by (Q) shed load(s)"},
	{"304","(Q) shed load(s). Right lane blocked"},
	{"305","(Q) shed load(s). Centre lane blocked"},
	{"306","(Q) shed load(s). Left lane blocked"},
	{"307","(Q) shed load(s). Hard shoulder blocked"},
	{"308","(Q) shed load(s). Two lanes blocked"},
	{"309","(Q) shed load(s). Three lanes blocked"},
	{"310","shed load. Delays (Q)"},
	{"311","shed load. Delays (Q) expected"},
	{"312","shed load. Long delays (Q)"},
	{"313","(Q) broken down vehicle(s). Stationary traffic"},
	{"314","(Q) broken down vehicle(s). Danger of stationary traffic"},
	{"315","(Q) broken down vehicle(s). Queuing traffic"},
	{"316","(Q) broken down vehicle(s). Danger of queuing traffic"},
	{"317","(Q) broken down vehicle(s). Slow traffic"},
	{"318","(Q) broken down vehicle(s). Slow traffic expected"},
	{"319","(Q) broken down vehicle(s). Heavy traffic"},
	{"320","(Q) broken down vehicle(s). Heavy traffic expected"},
	{"321","(Q) broken down vehicle(s). Traffic flowing freely"},
	{"322","(Q) broken down vehicle(s). Traffic building up"},
	{"323","blocked by (Q) broken down vehicle(s)."},
	{"324","(Q) broken down vehicle(s). Right lane blocked"},
	{"325","(Q) broken down lane vehicle(s). Centre lane blocked"},
	{"326","(Q) broken down vehicle(s). Left lane blocked"},
	{"327","(Q) broken down vehicle(s). Hard shoulder blocked"},
	{"328","(Q) broken down vehicle(s). Two lanes blocked"},
	{"329","(Q) broken down vehicle(s). Three lanes blocked"},
	{"330","broken down vehicle. Delays (Q)"},
	{"331","broken down vehicle. Delays (Q) expected"},
	{"332","broken down vehicle. Long delays (Q)"},
	{"333","accident cleared"},
	{"334","message cancelled"},
	{"335","accident involving (a/Q) bus(es)"},
	{"336","(Q) oil spillage accident(s)"},
	{"337","(Q) overturned vehicle(s)"},
	{"338","(Q) overturned heavy lorr(y/ies)"},
	{"339","(Q) jack-knifed trailer(s)"},
	{"340","(Q) jack-knifed caravan(s)"},
	{"341","(Q) jack-knifed articulated lorr(y/ies)"},
	{"342","(Q) vehicle(s) spun around"},
	{"343","(Q) earlier accident(s)"},
	{"344","accident investigation work"},
	{"345","(Q) secondary accident(s)"},
	{"346","(Q) broken down bus(es)"},
	{"347","(Q) over-height vehicle(s)"},
	{"348","(Q) accident(s). Stationary traffic for 3 km"},
	{"349","(Q) accident(s). Queuing traffic for 3 km"},
	{"350","(Q) accident(s). Slow traffic for 3 km"},
	{"351","(Q) accident(s) in roadworks area"},
	{"352","vehicles slowing to look at (Q) accident(s). Stationary traffic for 3 km"},
	{"353","vehicles slowing to look at (Q) accident(s). Queuing traffic for 3 km"},
	{"354","vehicles slowing to look at (Q) accident(s). Slow traffic for 3 km"},
	{"355","vehicles slowing to look at (Q) accident(s). Danger"},
	{"356","(Q) shed load(s). Stationary traffic for 3 km"},
	{"357","(Q) shed load(s). Queuing traffic for 3 km"},
	{"358","(Q) shed load(s). Slow traffic for 3 km"},
	{"359","(Q) shed load(s). Danger"},
	{"360","(Q) overturned vehicle(s). Stationary traffic"},
	{"361","(Q) overturned vehicle(s). Danger of stationary traffic"},
	{"362","(Q) overturned vehicle(s). Queuing traffic"},
	{"363","(Q) overturned vehicle(s). Danger of queuing traffic"},
	{"364","(Q) overturned vehicle(s). Slow traffic"},
	{"365","(Q) overturned vehicle(s). Slow traffic expected"},
	{"366","(Q) overturned vehicle(s). Heavy traffic"},
	{"367","(Q) overturned vehicle(s). Heavy traffic expected"},
	{"368","(Q) overturned vehicle(s). Traffic building up"},
	{"369","blocked by (Q) overturned vehicle(s)"},
	{"370","(Q) overturned vehicle(s). Right lane blocked"},
	{"371","(Q) overturned vehicle(s). Centre lane blocked"},
	{"372","(Q) overturned vehicle(s). Left lane blocked"},
	{"373","(Q) overturned vehicle(s). Two lanes blocked"},
	{"374","(Q) overturned vehicle(s). Three lanes blocked"},
	{"375","overturned vehicle. Delays (Q)"},
	{"376","overturned vehicle. Delays (Q) expected"},
	{"377","overturned vehicle. Long delays (Q)"},
	{"378","(Q) overturned vehicle(s). Danger"},
	{"379","Stationary traffic due to (Q) earlier accident(s)"},
	{"380","Danger of stationary traffic due to (Q) earlier accident(s)"},
	{"381","Queuing traffic due to (Q) earlier accident(s)"},
	{"382","Danger of queuing traffic due to (Q) earlier accident(s)"},
	{"383","Slow traffic due to (Q) earlier accident(s)"},
	{"384",""},
	{"385","Heavy traffic due to (Q) earlier accident(s)"},
	{"386",""},
	{"387","Traffic building up due to (Q) earlier accident(s)"},
	{"388","Delays (Q) due to earlier accident"},
	{"389",""},
	{"390","Long delays (Q) due to earlier accident"},
	{"391","accident investigation work. Danger"},
	{"392","(Q) secondary accident(s). Danger"},
	{"393","(Q) broken down vehicle(s). Danger"},
	{"394","(Q) broken down heavy lorr(y/ies). Danger"},
	{"395","road cleared"},
	{"396","incident cleared"},
	{"397","rescue and recovery work in progress"},
	{"398",""},
	{"399","message cancelled"},
	{"400",""},
	{"401","Closed"},
	{"402","blocked"},
	{"403","closed for heavy vehicles (over Q)"},
	{"404","no through traffic for heavy lorries (over Q)"},
	{"405","no through traffic"},
	{"406","(Q th) entry slip road closed"},
	{"407","(Q th) exit slip road closed"},
	{"408","slip roads closed"},
	{"409","slip road restrictions"},
	{"410","closed ahead. Stationary traffic"},
	{"411","closed ahead. Stationary traffic for 1 km"},
	{"412","closed ahead. Stationary traffic for 2 km"},
	{"413","closed ahead. Stationary traffic for 4 km"},
	{"414","closed ahead. Stationary traffic for 6 km"},
	{"415","closed ahead. Stationary traffic for 10 km"},
	{"416","closed ahead. Danger of stationary traffic"},
	{"417","closed ahead. Queuing traffic"},
	{"418","closed ahead. Queuing traffic for 1 km"},
	{"419","closed ahead. Queuing traffic for 2 km"},
	{"420","closed ahead. Queuing traffic for 4 km"},
	{"421","closed ahead. Queuing traffic for 6 km"},
	{"422","closed ahead. Queuing traffic for 10 km"},
	{"423","closed ahead. Danger of queuing traffic"},
	{"424","closed ahead. Slow traffic"},
	{"425","closed ahead. Slow traffic for 1 km"},
	{"426","closed ahead. Slow traffic for 2 km"},
	{"427","closed ahead. Slow traffic for 4 km"},
	{"428","closed ahead. Slow traffic for 6 km"},
	{"429","closed ahead. Slow traffic for 10 km"},
	{"430","closed ahead. Slow traffic expected"},
	{"431","closed ahead. Heavy traffic"},
	{"432","closed ahead. Heavy traffic expected"},
	{"433","closed ahead. Traffic flowing freely"},
	{"434","closed ahead. Traffic building up"},
	{"435","closed ahead. Delays (Q)"},
	{"436","closed ahead. Delays (Q) expected"},
	{"437","closed ahead. Long delays (Q)"},
	{"438","blocked ahead. Stationary traffic"},
	{"439","blocked ahead. Stationary traffic for 1 km"},
	{"440","blocked ahead. Stationary traffic for 2 km"},
	{"441","blocked ahead. Stationary traffic for 4 km"},
	{"442","blocked ahead. Stationary traffic for 6 km"},
	{"443","blocked ahead. Stationary traffic for 10 km"},
	{"444","blocked ahead. Danger of stationary traffic"},
	{"445","blocked ahead. Queuing traffic"},
	{"446","blocked ahead. Queuing traffic for 1 km"},
	{"447","blocked ahead. Queuing traffic for 2 km"},
	{"448","blocked ahead. Queuing traffic for 4 km"},
	{"449","blocked ahead. Queuing traffic for 6 km"},
	{"450","blocked ahead. Queuing traffic for 10 km"},
	{"451","blocked ahead. Danger of queuing traffic"},
	{"452","blocked ahead. Slow traffic"},
	{"453","blocked ahead. Slow traffic for 1 km"},
	{"454","blocked ahead. Slow traffic for 2 km"},
	{"455","blocked ahead. Slow traffic for 4 km"},
	{"456","blocked ahead. Slow traffic for 6 km"},
	{"457","blocked ahead. Slow traffic for 10 km"},
	{"458","blocked ahead. Slow traffic expected"},
	{"459","blocked ahead. Heavy traffic"},
	{"460","blocked ahead. Heavy traffic expected"},
	{"461","blocked ahead. Traffic flowing freely"},
	{"462","blocked ahead. Traffic building up"},
	{"463","blocked ahead. Delays (Q)"},
	{"464","blocked ahead. Delays (Q) expected"},
	{"465","blocked ahead. Long delays (Q)"},
	{"466","slip roads reopened"},
	{"467","reopened"},
	{"468","message cancelled"},
	{"469","closed ahead"},
	{"470","blocked ahead"},
	{"471","(Q) entry slip road(s) closed"},
	{"472","(Q th) entry slip road blocked"},
	{"473","entry blocked"},
	{"474","(Q) exit slip road(s) closed"},
	{"475","(Q th) exit slip road blocked"},
	{"476","exit blocked"},
	{"477","slip roads blocked"},
	{"478","connecting carriageway closed"},
	{"479","parallel carriageway closed"},
	{"480","right-hand parallel carriageway closed"},
	{"481","left-hand parallel carriageway closed"},
	{"482","express lanes closed"},
	{"483","through traffic lanes closed"},
	{"484","local lanes closed"},
	{"485","connecting carriageway blocked"},
	{"486","parallel carriageway blocked"},
	{"487","right-hand parallel carriageway blocked"},
	{"488","left-hand parallel carriageway blocked"},
	{"489","express lanes blocked"},
	{"490","through traffic lanes blocked"},
	{"491","local lanes blocked"},
	{"492","no motor vehicles"},
	{"493","restrictions"},
	{"494","closed for heavy lorries (over Q)"},
	{"495","closed ahead. Stationary traffic for 3 km"},
	{"496","closed ahead. Queuing traffic for 3 km"},
	{"497","closed ahead. Slow traffic for 3 km"},
	{"498","blocked ahead. Stationary traffic for 3 km"},
	{"499","blocked ahead. Queuing traffic for 3 km"},
	{"500","(Q) lane(s) closed"},
	{"501","(Q) right lane(s) closed"},
	{"502","(Q) centre lane(s) closed"},
	{"503","(Q) left lane(s) closed"},
	{"504","hard shoulder closed"},
	{"505","two lanes closed"},
	{"506","three lanes closed"},
	{"507","(Q) right lane(s) blocked"},
	{"508","(Q) centre lane(s) blocked"},
	{"509","(Q) left lane(s) blocked"},
	{"510","hard shoulder blocked"},
	{"511","Two lanes blocked"},
	{"512","three lanes blocked"},
	{"513","single alternate line traffic"},
	{"514","carriageway reduced (from Q lanes) one lane"},
	{"515","carriageway reduced (from Q lanes) two lanes"},
	{"516","carriageway reduced (from Q lanes) three lanes"},
	{"517","contraflow"},
	{"518","narrow lanes"},
	{"519","contraflow with narrow lanes"},
	{"520","(Q) lane(s) blocked"},
	{"521","(Q) lanes closed. Stationary traffic"},
	{"522","(Q) lanes closed. Stationary traffic for 1 km"},
	{"523","(Q) lanes closed. Stationary traffic for 2 km"},
	{"524","(Q) lanes closed. Stationary traffic for 4 km"},
	{"525","(Q) lanes closed. Stationary traffic for 6 km"},
	{"526","(Q) lanes closed. Stationary traffic for 10 km"},
	{"527","(Q) lanes closed. Danger of stationary traffic"},
	{"528","(Q) lanes closed. Queuing traffic"},
	{"529","(Q) lanes closed. Queuing traffic for 1 km"},
	{"530","(Q) lanes closed. Queuing traffic for 2 km"},
	{"531","(Q) lanes closed. Queuing traffic for 4 km"},
	{"532","(Q) lanes closed. Queuing traffic for 6 km"},
	{"533","(Q) lanes closed. Queuing traffic for 10 km"},
	{"534","(Q) lanes closed. Danger of queuing traffic"},
	{"535","(Q) lanes closed. Slow traffic"},
	{"536","(Q) lanes closed. Slow traffic for 1 km"},
	{"537","(Q) lanes closed. Slow traffic for 2 km"},
	{"538","(Q) lanes closed. Slow traffic for 4 km"},
	{"539","(Q) lanes closed. Slow traffic for 6 km"},
	{"540","(Q) lanes closed. Slow traffic for 10 km"},
	{"541","(Q) lanes closed. Slow traffic expected"},
	{"542","(Q) lanes closed. Heavy traffic"},
	{"543","(Q) lanes closed. Heavy traffic expected"},
	{"544","(Q)lanes closed. Traffic flowing freely"},
	{"545","(Q)lanes closed. Traffic building up"},
	{"546","carriageway reduced (from Q lanes) to one lane. Stationary traffic"},
	{"547","carriageway reduced (from Q lanes) to one lane. Danger of stationary traffic"},
	{"548","carriageway reduced (from Q lanes) to one lane. Queuing traffic"},
	{"549","carriageway reduced (from Q lanes) to one lane. Danger of queuing traffic"},
	{"550","carriageway reduced (from Q lanes) to one lane. Slow traffic"},
	{"551","carriageway reduced (from Q lanes) to one lane. Slow traffic expected"},
	{"552","carriageway reduced (from Q lanes) to one lane. Heavy traffic"},
	{"553","carriageway reduced (from Q lanes) to one lane. Heavy traffic expected"},
	{"554","carriageway reduced (from Q lanes) to one lane. Traffic flowing freely"},
	{"555","carriageway reduced (from Q lanes) to one lane. Traffic building up"},
	{"556","carriageway reduced (from Q lanes) to two lanes. Stationary traffic"},
	{"557","carriageway reduced (from Q lanes) to two lanes. Danger of stationary traffic"},
	{"558","carriageway reduced (from Q lanes) to two lanes. Queuing traffic"},
	{"559","carriageway reduced (from Q lanes) to two lanes. Danger of queuing traffic"},
	{"560","carriageway reduced (from Q lanes) to two lanes. Slow traffic"},
	{"561","carriageway reduced (from Q lanes) to two lanes. Slow traffic expected"},
	{"562","carriageway reduced (from Q lanes) to two lanes. Heavy traffic"},
	{"563","carriageway reduced (from Q lanes) to two lanes. Heavy traffic expected"},
	{"564","carriageway reduced (from Q lanes) to two lanes. Traffic flowing freely"},
	{"565","carriageway reduced (from Q lanes) to two lanes. Traffic building up"},
	{"566","carriageway reduced (from Q lanes) three lanes. Stationary traffic"},
	{"567","carriageway reduced (from Q lanes) three lanes. Danger of stationary traffic"},
	{"568","carriageway reduced (from Q lanes) three lanes. Queuing traffic"},
	{"569","carriageway reduced (from Q lanes) three lanes. Danger of queuing traffic"},
	{"570","carriageway reduced (from Q lanes) to three lanes. Slow traffic"},
	{"571","carriageway reduced (from Q lanes) to three lanes. Slow traffic expected"},
	{"572","carriageway reduced (from Q lanes) to three lanes. Heavy traffic"},
	{"573","carriageway reduced (from Q lanes) to three lanes. Heavy traffic expected"},
	{"574","carriageway reduced (from Q lanes) to three lanes. Traffic flowing freely"},
	{"575","carriageway reduced (from Q lanes) to three lanes. Traffic building up"},
	{"576","contraflow. Stationary traffic"},
	{"577","contraflow. Stationary traffic for 1 km"},
	{"578","contraflow. Stationary traffic for 2 km"},
	{"579","contraflow. Stationary traffic for 4 km"},
	{"580","contraflow. Stationary traffic for 6 km"},
	{"581","contraflow. Stationary traffic for 10 km"},
	{"582","contraflow. Danger of stationary traffic"},
	{"583","contraflow. Queuing traffic"},
	{"584","contraflow. Queuing traffic for1km"},
	{"585","contraflow. Queuing traffic for2km"},
	{"586","contraflow. Queuing traffic for4km"},
	{"587","contraflow. Queuing traffic for6km"},
	{"588","contraflow. Queuing traffic for 10 km"},
	{"589","contraflow. Danger of queuing traffic"},
	{"590","contraflow. Slow traffic"},
	{"591","contraflow. Slow traffic for 1 km"},
	{"592","contraflow. Slow traffic for 2 km"},
	{"593","contraflow. Slow traffic for 4 km"},
	{"594","contraflow. Slow traffic for 6 km"},
	{"595","contraflow. Slow traffic for 10 km"},
	{"596","contraflow. Slow traffic expected"},
	{"597","contraflow. Heavy traffic"},
	{"598","contraflow. Heavy traffic expected"},
	{"599","contraflow. Traffic flowing freely"},
	{"600","contraflow. Traffic building up"},
	{"601","contraflow. Carriageway reduced (from Q lanes) to one lane"},
	{"602","contraflow. Carriageway reduced (from Q lanes) to two lanes"},
	{"603","contraflow. Carriageway reduced (from Q lanes) to three lanes"},
	{"604","narrow lanes. Stationary traffic"},
	{"605","narrow lanes. Danger of stationary traffic"},
	{"606","narrow lanes. Queuing traffic"},
	{"607","narrow lanes. Danger of queuing traffic"},
	{"608","narrow lanes. Slow traffic"},
	{"609","narrow lanes. Slow traffic expected"},
	{"610","narrow lanes. Heavy traffic"},
	{"611","narrow lanes. Heavy traffic expected"},
	{"612","narrow lanes. Traffic flowing freely"},
	{"613","narrow lanes. Traffic building up"},
	{"614","contraflow with narrow lanes. Stationary traffic"},
	{"615","contraflow with narrow lanes. Danger of stationary traffic"},
	{"616","contraflow with narrow lanes. Queuing traffic"},
	{"617","contraflow with narrow lanes. Danger of queuing traffic"},
	{"618","contraflow with narrow lanes. Slow traffic"},
	{"619","contraflow with narrow lanes. Slow traffic expected"},
	{"620","contraflow with narrow lanes. Heavy traffic"},
	{"621","contraflow with narrow lanes. Heavy traffic expected"},
	{"622","contraflow with narrow lanes. Traffic flowing freely"},
	{"623","contraflow with narrow lanes. Traffic building up"},
	{"624","lane closures removed"},
	{"625","message cancelled"},
	{"626","blocked ahead. Slow traffic for 3 km"},
	{"627","no motor vehicles without catalytic converters"},
	{"628","no motor vehicles with even-numbered registration plates"},
	{"629","no motor vehicles with odd-numbered registration plates"},
	{"630","open"},
	{"631","road cleared"},
	{"632","entry reopened"},
	{"633","exit reopened"},
	{"634","all carriageways reopened"},
	{"635","motor vehicle restrictions lifted"},
	{"636","traffic restrictions lifted {reopened for all traffic}"},
	{"637","emergency lane closed"},
	{"638","turning lane closed"},
	{"639","crawler lane closed"},
	{"640","slow vehicle lane closed"},
	{"641","one lane closed"},
	{"642","emergency lane blocked"},
	{"643","turning lane blocked"},
	{"644","crawler lane blocked"},
	{"645","slow vehicle lane blocked"},
	{"646","One lane blocked"},
	{"647","(Q person) carpool lane in operation"},
	{"648","(Q person) carpool lane closed"},
	{"649","(Q person) carpool lane blocked"},
	{"650","carpool restrictions changed (to Q persons per vehicle)"},
	{"651","(Q) lanes closed. Stationary traffic for 3 km"},
	{"652","(Q) lanes closed. Queuing traffic for 3 km"},
	{"653","(Q) lanes closed. Slow traffic for 3 km"},
	{"654","contraflow. Stationary traffic for 3 km"},
	{"655","contraflow. Queuing traffic for3km"},
	{"656","contraflow. Slow traffic for 3 km"},
	{"657","lane blockages cleared"},
	{"658","contraflow removed"},
	{"659","(Q person) carpool restrictions lifted"},
	{"660","lane restrictions lifted"},
	{"661","use of hard shoulder allowed"},
	{"662","normal lane regulations restored"},
	{"663","all carriageways cleared"},
	{"664","carriageway closed"},
	{"665","both directions closed"},
	{"666","intermittent short term closures"},
	{"667",""},
	{"668",""},
	{"669",""},
	{"670",""},
	{"671","bus lane available for carpools (with at least Q occupants)"},
	{"672","message cancelled"},
	{"673","message cancelled"},
	{"674",""},
	{"675",""},
	{"676","bus lane blocked"},
	{"677",""},
	{"678","heavy vehicle lane closed"},
	{"679","heavy vehicle lane blocked"},
	{"680","reopened for through traffic"},
	{"681","(Q) snowploughs"},
	{"682",""},
	{"683",""},
	{"684",""},
	{"685",""},
	{"686",""},
	{"687",""},
	{"688",""},
	{"689",""},
	{"690",""},
	{"691",""},
	{"692",""},
	{"693",""},
	{"694",""},
	{"695",""},
	{"696",""},
	{"697",""},
	{"698",""},
	{"699",""},
	{"700",""},
	{"701","(Q sets of) roadworks"},
	{"702","(Q sets of) major roadworks"},
	{"703","(Q sets of) maintenance work"},
	{"704","(Q sections of) resurfacing work"},
	{"705","(Q sets of) central reservation work"},
	{"706","(Q sets of) road marking work"},
	{"707","bridge maintenance work (at Q bridges)"},
	{"708","(Q sets of) temporary traffic lights"},
	{"709","(Q sections of) blasting work"},
	{"710","(Q sets of) roadworks. Stationary traffic"},
	{"711","(Q sets of) roadworks. Stationary traffic for 1 km"},
	{"712","(Q sets of) roadworks. Stationary traffic for 2 km"},
	{"713","(Q sets of) roadworks. Stationary traffic for 4 km"},
	{"714","(Q sets of) roadworks. Stationary traffic for 6 km"},
	{"715","(Q sets of) roadworks. Stationary traffic for 10 km"},
	{"716","(Q sets of) roadworks. Danger of stationary traffic"},
	{"717","(Q sets of) roadworks. Queuing traffic"},
	{"718","(Q sets of) roadworks. Queuing traffic for 1 km"},
	{"719","(Q sets of) roadworks. Queuing traffic for 2 km"},
	{"720","(Q sets of) roadworks. Queuing traffic for 4 km"},
	{"721","(Q sets of) roadworks. Queuing traffic for 6 km"},
	{"722","(Q sets of) roadworks. Queuing traffic for 10 km"},
	{"723","(Q sets of) roadworks. Danger of queuing traffic"},
	{"724","(Q sets of) roadworks. Slow traffic"},
	{"725","(Q sets of) roadworks. Slow traffic for 1 km"},
	{"726","(Q sets of) roadworks. Slow traffic for 2 km"},
	{"727","(Q sets of) roadworks. Slow traffic for 4 km"},
	{"728","(Q sets of) roadworks. Slow traffic for 6 km"},
	{"729","(Q sets of) roadworks. Slow traffic for 10 km"},
	{"730","(Q sets of) roadworks. Slow traffic expected"},
	{"731","(Q sets of) roadworks. Heavy traffic"},
	{"732","(Q sets of) roadworks. Heavy traffic expected"},
	{"733","(Q sets of) roadworks. Traffic flowing freely"},
	{"734","(Q sets of) roadworks. Traffic building up"},
	{"735","closed due to (Q sets of) roadworks"},
	{"736","(Q sets of) roadworks. Right lane closed"},
	{"737","(Q sets of) roadworks. Centre lane closed"},
	{"738","(Q sets of) roadworks. Left lane closed"},
	{"739","(Q sets of) roadworks. Hard shoulder closed"},
	{"740","(Q sets of) roadworks. Two lanes closed"},
	{"741","(Q sets of) roadworks. Three lanes closed"},
	{"742","(Q sets of) roadworks. Single alternate line traffic"},
	{"743","roadworks. Carriageway reduced (from Q lanes) to one lane"},
	{"744","roadworks. Carriageway reduced (from Q lanes) to two lanes"},
	{"745","roadworks. Carriageway reduced (from Q lanes) to three lanes"},
	{"746","(Q sets of) roadworks. Contraflow"},
	{"747","roadworks. Delays (Q)"},
	{"748","roadworks. Delays (Q) expected"},
	{"749","roadworks. Long delays (Q)"},
	{"750","(Q sections of) resurfacing work. Stationary traffic"},
	{"751","(Q sections of) resurfacing work. Stationary traffic for 1 km"},
	{"752","(Q sections of) resurfacing work. Stationary traffic for 2 km"},
	{"753","(Q sections of) resurfacing work. Stationary traffic for 4 km"},
	{"754","(Q sections of) resurfacing work. Stationary traffic for 6 km"},
	{"755","(Q sections of) resurfacing work. Stationary traffic for 10 km"},
	{"756","(Q sections of) resurfacing work. Danger of stationary traffic"},
	{"757","(Q sections of) resurfacing work. Queuing traffic"},
	{"758","(Q sections of) resurfacing work. Queuing traffic for 1 km"},
	{"759","(Q sections of) resurfacing work. Queuing traffic for 2 km"},
	{"760","(Q sections of) resurfacing work. Queuing traffic for 4 km"},
	{"761","(Q sections of) resurfacing work. Queuing traffic for 6 km"},
	{"762","(Q sections of) resurfacing work. Queuing traffic for 10 km"},
	{"763","(Q sections of) resurfacing work. Danger of queuing traffic"},
	{"764","(Q sections of) resurfacing work. traffic"},
	{"765","(Q sections of) resurfacing work. traffic for 1 km"},
	{"766","(Q sections of) resurfacing work. traffic for 2 km"},
	{"767","(Q sections of) resurfacing work. traffic for 4 km"},
	{"768","(Q sections of) resurfacing work. traffic for 6 km"},
	{"769","(Q sections of) resurfacing work. traffic for 10 km"},
	{"770","(Q sections of) resurfacing work. Slow traffic expected"},
	{"771","(Q sections of) resurfacing work. Heavy traffic"},
	{"772","(Q sections of) resurfacing work. Heavy traffic expected"},
	{"773","(Q sections of) resurfacing work. Traffic flowing freely"},
	{"774","(Q sections of) resurfacing work. Traffic building up"},
	{"775","(Q sections of) resurfacing work. Single alternate line traffic"},
	{"776","resurfacing work. Carriageway reduced (from Q lanes) to one lane"},
	{"777","resurfacing work. Carriageway reduced (from Q lanes) to two lanes"},
	{"778","resurfacing work. Carriageway reduced (from Q lanes) to three lanes"},
	{"779","(Q sections of) resurfacing work. Contraflow"},
	{"780","resurfacing work. Delays (Q)"},
	{"781","resurfacing work. Delays (Q) expected"},
	{"782","resurfacing work. Long delays (Q)"},
	{"783","(Q sets of) road marking work. Stationary traffic"},
	{"784","(Q sets of) road marking work. Danger of stationary traffic"},
	{"785","(Q sets of) road marking work. Queuing traffic"},
	{"786","(Q sets of) road marking work. Danger of queuing traffic"},
	{"787","(Q sets of) road marking work. Slow traffic"},
	{"788","(Q sets of) road marking work. Slow traffic expected"},
	{"789","(Q sets of) road marking work. Heavy traffic"},
	{"790","(Q sets of) road marking work. Heavy traffic expected"},
	{"791","(Q sets of) road marking work. Traffic flowing freely"},
	{"792","(Q sets of) road marking work. Traffic building up"},
	{"793","(Q sets of) road marking work. Right lane closed"},
	{"794","(Q sets of) road marking work. Centre lane closed"},
	{"795","(Q sets of) road marking work. Left lane closed"},
	{"796","(Q sets of) road marking work. Hard shoulder closed"},
	{"797","(Q sets of) road marking work. Two lanes closed"},
	{"798","(Q sets of) road marking work. Three lanes closed"},
	{"799","closed for bridge demolition work (at Q bridges)"},
	{"800","roadworks cleared"},
	{"801","message cancelled"},
	{"802","(Q sets of) long-term roadworks"},
	{"803","(Q sets of) construction work"},
	{"804","(Q sets of) slow moving maintenance vehicles"},
	{"805","bridge demolition work (at Q bridges)"},
	{"806","(Q sets of) water main work"},
	{"807","(Q sets of) gas main work"},
	{"808","(Q sets of) work on buried cables"},
	{"809","(Q sets of) work on buried services"},
	{"810","new roadworks layout"},
	{"811","new road layout"},
	{"812","(Q sets of) roadworks. Stationary traffic for 3 km"},
	{"813","(Q sets of) roadworks. Queuing traffic for 3 km"},
	{"814","(Q sets of) roadworks. Slow traffic for 3 km"},
	{"815","(Q sets of) roadworks during the day time"},
	{"816","(Q sets of) roadworks during off-peak periods"},
	{"817","(Q sets of) roadworks during the night"},
	{"818","(Q sections of) resurfacing work. Stationary traffic for 3 km"},
	{"819","(Q sections of) resurfacing work. Queuing traffic for 3 km"},
	{"820","(Q sections of) resurfacing work. traffic for 3 km"},
	{"821","(Q sets of) resurfacing work during the day time"},
	{"822","(Q sets of) resurfacing work during off- peak periods"},
	{"823","(Q sets of) resurfacing work during the night"},
	{"824","(Q sets of) road marking work. Danger"},
	{"825","(Q sets of) slow moving maintenance vehicles. Stationary traffic"},
	{"826","(Q sets of) slow moving maintenance vehicles. Danger of stationary traffic"},
	{"827","(Q sets of) slow moving maintenance vehicles. Queuing traffic"},
	{"828","(Q sets of) slow moving maintenance vehicles. Danger of queuing traffic"},
	{"829","(Q sets of) slow moving maintenance vehicles. Slow traffic"},
	{"830","(Q sets of) slow moving maintenance vehicles. Slow traffic expected"},
	{"831","(Q sets of) slow moving maintenance vehicles. Heavy traffic"},
	{"832","(Q sets of) slow moving maintenance vehicles. Heavy traffic expected"},
	{"833","(Q sets of) slow moving maintenance vehicles. Traffic flowing freely"},
	{"834","(Q sets of) slow moving maintenance vehicles. Traffic building up"},
	{"835","(Q sets of) slow moving maintenance vehicles. Right lane closed"},
	{"836","(Q sets of) slow moving maintenance vehicles. Centre lane closed"},
	{"837","(Q sets of) slow moving maintenance vehicles. Left lane closed"},
	{"838","(Q sets of) slow moving maintenance vehicles. Two lanes closed"},
	{"839","(Q sets of) slow moving maintenance vehicles. Three lanes closed"},
	{"840","water main work. Delays (Q)"},
	{"841","water main work. Delays (Q) expected"},
	{"842","water main work. Long delays (Q)"},
	{"843","gas main work. Delays (Q)"},
	{"844","gas main work. Delays (Q) expected"},
	{"845","gas main work. Long delays (Q)"},
	{"846","work on buried cables. Delays (Q)"},
	{"847","work on buried cables. Delays (Q) expected"},
	{"848","work on buried cables. Long delays (Q)"},
	{"849","work on buried services. Delays (Q)"},
	{"850","work on buried services. Delays (Q) expected"},
	{"851","work on buried services. Long delays (Q)"},
	{"852","construction traffic merging"},
	{"853","roadwork clearance in progress"},
	{"854","maintenance work cleared"},
	{"855","road layout unchanged"},
	{"856","construction traffic merging. Danger"},
	{"857","(Q) unprotected accident area(s)"},
	{"858","danger of (Q) unprotected accident area(s)"},
	{"859","(Q) unlit vehicle(s) on the road"},
	{"860","danger of (Q) unlit vehicle(s) on the road"},
	{"861","snow and ice debris"},
	{"862","danger of snow and ice debris"},
	{"863",""},
	{"864",""},
	{"865",""},
	{"866",""},
	{"867",""},
	{"868",""},
	{"869",""},
	{"870",""},
	{"871",""},
	{"872",""},
	{"873",""},
	{"874",""},
	{"875",""},
	{"876",""},
	{"877",""},
	{"878",""},
	{"879",""},
	{"880",""},
	{"881",""},
	{"882",""},
	{"883",""},
	{"884",""},
	{"885",""},
	{"886",""},
	{"887",""},
	{"888",""},
	{"889",""},
	{"890",""},
	{"891",""},
	{"892",""},
	{"893",""},
	{"894",""},
	{"895",""},
	{"896",""},
	{"897",""},
	{"898","obstruction warning withdrawn"},
	{"899","clearance work in progress, road free again"},
	{"900","flooding expected"},
	{"901","(Q) obstruction(s) on roadway {something that does block the road or part of it}"},
	{"902","(Q) obstructions on the road. Danger"},
	{"903","spillage on the road"},
	{"904","storm damage"},
	{"905","(Q) fallen trees"},
	{"906","(Q) fallen trees. Danger"},
	{"907","flooding"},
	{"908","flooding. Danger"},
	{"909","flash floods"},
	{"910","danger of flash floods"},
	{"911","avalanches"},
	{"912","avalanche risk"},
	{"913","rockfalls"},
	{"914","landslips"},
	{"915","earthquake damage"},
	{"916","road surface in poor condition"},
	{"917","subsidence"},
	{"918","(Q) collapsed sewer(s)"},
	{"919","burst water main"},
	{"920","gas leak"},
	{"921","serious fire"},
	{"922","animals on roadway"},
	{"923","animals on the road. Danger"},
	{"924","clearance work"},
	{"925","blocked by storm damage"},
	{"926","blocked by (Q) fallen trees"},
	{"927","(Q) fallen tree(s). Passable with care"},
	{"928","flooding. Stationary traffic"},
	{"929","flooding. Danger of stationary traffic"},
	{"930","flooding. Queuing traffic"},
	{"931","flooding. Danger of queuing traffic"},
	{"932","flooding. Slow traffic"},
	{"933","flooding. Slow traffic expected"},
	{"934","flooding. Heavy traffic"},
	{"935","flooding. Heavy traffic expected"},
	{"936","flooding. Traffic flowing freely"},
	{"937","flooding. Traffic building up"},
	{"938","closed due to flooding"},
	{"939","flooding. Delays (Q)"},
	{"940","flooding. Delays (Q) expected"},
	{"941","flooding. Long delays (Q)"},
	{"942","flooding. Passable with care"},
	{"943","closed due to avalanches"},
	{"944","avalanches. Passable with care (above Q hundred metres)"},
	{"945","closed due to rockfalls"},
	{"946","rockfalls. Passable with care"},
	{"947","road closed due to landslips"},
	{"948","landslips. Passable with care"},
	{"949","closed due to subsidence"},
	{"950","subsidence. Single alternate line traffic"},
	{"951","subsidence. Carriageway reduced (from Q lanes) to one lane"},
	{"952","subsidence. Carriageway reduced (from Q lanes) to two lanes"},
	{"953","subsidence. Carriageway reduced (from Q lanes) to three lanes"},
	{"954","subsidence. Contraflow in operation"},
	{"955","subsidence. Passable with care"},
	{"956","closed due to sewer collapse"},
	{"957","road closed due to burst water main"},
	{"958","burst water main. Delays (Q)"},
	{"959","burst water main. Delays (Q) expected"},
	{"960","burst water main. Long delays (Q)"},
	{"961","closed due to gas leak"},
	{"962","gas leak. Delays (Q)"},
	{"963","gas leak. Delays (Q) expected"},
	{"964","gas leak. Long delays (Q)"},
	{"965","closed due to serious fire"},
	{"966","serious fire. Delays (Q)"},
	{"967","serious fire. Delays (Q) expected"},
	{"968","serious fire. Long delays (Q)"},
	{"969","closed for clearance work"},
	{"970","road free again"},
	{"971","message cancelled"},
	{"972","storm damage expected"},
	{"973","fallen power cables"},
	{"974","sewer overflow"},
	{"975","ice build-up"},
	{"976","mud slide"},
	{"977","grass fire"},
	{"978","air crash"},
	{"979","rail crash"},
	{"980","blocked by (Q) obstruction(s) on the road"},
	{"981","(Q) obstructions on the road. Passable with care"},
	{"982","blocked due to spillage on roadway"},
	{"983","spillage on the road. Passable with care"},
	{"984","spillage on the road. Danger"},
	{"985","storm damage. Passable with care"},
	{"986","storm damage. Danger"},
	{"987","blocked by fallen power cables"},
	{"988","fallen power cables. Passable with care"},
	{"989","fallen power cables. Danger"},
	{"990","sewer overflow. Danger"},
	{"991","flash floods. Danger"},
	{"992","avalanches. Danger"},
	{"993","closed due to avalanche risk"},
	{"994","avalanche risk. Danger"},
	{"995","closed due to ice build-up"},
	{"996","ice build-up. Passable with care (above Q hundred metres)"},
	{"997","ice build-up. Single alternate traffic"},
	{"998","rockfalls. Danger"},
	{"999","landslips. Danger"},
	{"1000","earthquake damage. Danger"},
	{"1001","hazardous driving conditions (above Q hundred metres)"},
	{"1002","danger of aquaplaning"},
	{"1003","slippery road (above Q hundred metres)"},
	{"1004","mud on road"},
	{"1005","leaves on road"},
	{"1006","ice (above Q hundred metres)"},
	{"1007","danger of ice (above Q hundred metres)"},
	{"1008","black ice (above Q hundred metres)"},
	{"1009","freezing rain (above Q hundred metres)"},
	{"1010","wet and icy roads (above Q hundred metres)"},
	{"1011","slush (above Q hundred metres)"},
	{"1012","snow on the road (above Q hundred metres)"},
	{"1013","packed snow (above Q hundred metres)"},
	{"1014","fresh snow (above Q hundred metres)"},
	{"1015","deep snow (above Q hundred metres)"},
	{"1016","snow drifts (above Q hundred metres)"},
	{"1017","slippery due to spillage on roadway"},
	{"1018","slippery road (above Q hundred metres) due to snow"},
	{"1019","slippery road (above Q hundred metres) due to frost"},
	{"1020","road blocked by snow (above Q hundred metres)"},
	{"1021","snow on the road. Carriageway reduced (from Q lanes) to one lane"},
	{"1022","snow on the road. Carriageway reduced (from Q lanes) to two lanes"},
	{"1023","snow on the road. Carriageway reduced (from Q lanes) to three lanes"},
	{"1024","conditions of road surface improved"},
	{"1025","message cancelled"},
	{"1026","subsidence. Danger"},
	{"1027","sewer collapse. Delays (Q)"},
	{"1028","sewer collapse. Delays (Q) expected"},
	{"1029","sewer collapse. Long delays (Q)"},
	{"1030","sewer collapse. Danger"},
	{"1031","burst water main. Danger"},
	{"1032","gas leak. Danger"},
	{"1033","serious fire. Danger"},
	{"1034","clearance work. Danger"},
	{"1035","impassable (above Q hundred metres)"},
	{"1036","almost impassable (above Q hundred metres)"},
	{"1037","extremely hazardous driving conditions (above Q hundred metres)"},
	{"1038","difficult driving conditions (above Q hundred metres)"},
	{"1039","passable with care (up to Q hundred metres)"},
	{"1040","passable (up to Q hundred metres)"},
	{"1041","surface water hazard"},
	{"1042","loose sand on road"},
	{"1043","loose chippings"},
	{"1044","oil on road"},
	{"1045","petrol on road"},
	{"1046",""},
	{"1047","icy patches (above Q hundred metres)"},
	{"1048","danger of icy patches (above Q hundred metres)"},
	{"1049",""},
	{"1050","danger of black ice (above Q hundred metres)"},
	{"1051",""},
	{"1052",""},
	{"1053",""},
	{"1054","slippery due to loose sand on roadway"},
	{"1055","mud on road. Danger"},
	{"1056","loose chippings. Danger"},
	{"1057","oil on road. Danger"},
	{"1058","petrol on road. Danger"},
	{"1059","road surface in poor condition. Danger"},
	{"1060","icy patches (above Q hundred metres) on bridges"},
	{"1061","danger of icy patches (above Q hundred metres) on bridges"},
	{"1062","icy patches (above Q hundred metres) on bridges, in shaded areas and on slip roads"},
	{"1063","impassable for heavy vehicles (over Q)"},
	{"1064","impassable (above Q hundred metres) for vehicles with trailers"},
	{"1065","driving conditions improved"},
	{"1066","rescue and recovery work in progress. Danger"},
	{"1067","large animals on roadway"},
	{"1068","herds of animals on roadway"},
	{"1069","skid hazard reduced"},
	{"1070","snow cleared"},
	{"1071",""},
	{"1072",""},
	{"1073","extremely hazardous driving conditions expected (above Q hundred meters)"},
	{"1074","freezing rain expected (above Q hundred metres)"},
	{"1075","danger of road being blocked by snow (above Q hundred metres)"},
	{"1076",""},
	{"1077",""},
	{"1078",""},
	{"1079","temperature falling rapidly (to Q)"},
	{"1080","extreme heat (up to Q)"},
	{"1081","extreme cold (of Q)"},
	{"1082","less extreme temperatures"},
	{"1083","current temperature (Q)"},
	{"1084","house fire"},
	{"1085",""},
	{"1086","vehicle stuck under bridge"},
	{"1087",""},
	{"1088",""},
	{"1089",""},
	{"1090",""},
	{"1091",""},
	{"1092",""},
	{"1093",""},
	{"1094",""},
	{"1095",""},
	{"1096",""},
	{"1097",""},
	{"1098",""},
	{"1099",""},
	{"1100",""},
	{"1101","heavy snowfall (Q)"},
	{"1102","heavy snowfall (Q). Visibility reduced to <30 m"},
	{"1103","heavy snowfall (Q). Visibility reduced to <50 m"},
	{"1104","snowfall (Q)"},
	{"1105","snowfall (Q). Visibility reduced to <100 m"},
	{"1106","hail (visibility reduced to Q)"},
	{"1107","sleet (visibility reduced to Q)"},
	{"1108","thunderstorms (visibility reduced to Q)"},
	{"1109","heavy rain (Q)"},
	{"1110","heavy rain (Q). Visibility reduced to <30 m"},
	{"1111","heavy rain (Q). Visibility reduced to <50 m"},
	{"1112","rain (Q)"},
	{"1113","rain (Q). Visibility reduced to <100 m"},
	{"1114","showers (visibility reduced to Q)"},
	{"1115","heavy frost"},
	{"1116","frost"},
	{"1117",""},
	{"1118",""},
	{"1119",""},
	{"1120",""},
	{"1121",""},
	{"1122",""},
	{"1123",""},
	{"1124",""},
	{"1125",""},
	{"1126","weather situation improved"},
	{"1127","message cancelled"},
	{"1128","winter storm (visibility reduced to Q)"},
	{"1129",""},
	{"1130","blizzard (visibility reduced to Q)"},
	{"1131",""},
	{"1132","damaging hail (visibility reduced to Q)"},
	{"1133",""},
	{"1134","heavy snowfall. Visibility reduced (to Q)"},
	{"1135","snowfall. Visibility reduced (to Q)"},
	{"1136","heavy rain. Visibility reduced (to Q)"},
	{"1137","rain. Visibility reduced (to Q)"},
	{"1138",""},
	{"1139",""},
	{"1140",""},
	{"1141",""},
	{"1142",""},
	{"1143",""},
	{"1144",""},
	{"1145",""},
	{"1146",""},
	{"1147",""},
	{"1148",""},
	{"1149",""},
	{"1150",""},
	{"1151",""},
	{"1152",""},
	{"1153",""},
	{"1154",""},
	{"1155",""},
	{"1156",""},
	{"1157",""},
	{"1158",""},
	{"1159",""},
	{"1160",""},
	{"1161",""},
	{"1162",""},
	{"1163",""},
	{"1164",""},
	{"1165","rain changing to snow"},
	{"1166","snow changing to rain"},
	{"1167",""},
	{"1168",""},
	{"1169",""},
	{"1170","heavy snowfall (Q) expected"},
	{"1171","heavy rain (Q) expected"},
	{"1172","weather expected to improve"},
	{"1173","blizzard (with visibility reduced to Q) expected"},
	{"1174","damaging hail (with visibility reduced to Q) expected"},
	{"1175","reduced visibility (to Q) expected"},
	{"1176","freezing fog expected (with visibility reduced to Q). Danger of slippery roads"},
	{"1177","dense fog (with visibility reduced to Q) expected"},
	{"1178","patchy fog (with visibility reduced to Q) expected"},
	{"1179","visibility expected to improve"},
	{"1180","adverse weather warning withdrawn"},
	{"1181",""},
	{"1182",""},
	{"1183",""},
	{"1184",""},
	{"1185",""},
	{"1186",""},
	{"1187",""},
	{"1188",""},
	{"1189",""},
	{"1190","severe smog"},
	{"1191","severe exhaust pollution"},
	{"1192",""},
	{"1193",""},
	{"1194",""},
	{"1195",""},
	{"1196",""},
	{"1197",""},
	{"1198",""},
	{"1199",""},
	{"1200",""},
	{"1201","tornadoes"},
	{"1202","hurricane force winds (Q)"},
	{"1203","gales (Q)"},
	{"1204","storm force winds (Q)"},
	{"1205","strong winds (Q)"},
	{"1206",""},
	{"1207",""},
	{"1208",""},
	{"1209","gusty winds (Q)"},
	{"1210","crosswinds (Q)"},
	{"1211","strong winds (Q) affecting high-sided vehicles"},
	{"1212","closed for high-sided vehicles due to strong winds (Q)"},
	{"1213","strong winds easing"},
	{"1214","message cancelled"},
	{"1215","restrictions for high-sided vehicles lifted"},
	{"1216",""},
	{"1217","tornado warning ended"},
	{"1218",""},
	{"1219",""},
	{"1220",""},
	{"1221",""},
	{"1222",""},
	{"1223",""},
	{"1224",""},
	{"1225",""},
	{"1226",""},
	{"1227",""},
	{"1228",""},
	{"1229",""},
	{"1230",""},
	{"1231",""},
	{"1232",""},
	{"1233",""},
	{"1234",""},
	{"1235",""},
	{"1236",""},
	{"1237",""},
	{"1238",""},
	{"1239",""},
	{"1240",""},
	{"1241",""},
	{"1242",""},
	{"1243",""},
	{"1244",""},
	{"1245",""},
	{"1246",""},
	{"1247",""},
	{"1248",""},
	{"1249",""},
	{"1250",""},
	{"1251",""},
	{"1252",""},
	{"1253",""},
	{"1254",""},
	{"1255",""},
	{"1256",""},
	{"1257",""},
	{"1258",""},
	{"1259",""},
	{"1260",""},
	{"1261",""},
	{"1262",""},
	{"1263",""},
	{"1264",""},
	{"1265",""},
	{"1266",""},
	{"1267",""},
	{"1268",""},
	{"1269",""},
	{"1270",""},
	{"1271",""},
	{"1272",""},
	{"1273",""},
	{"1274",""},
	{"1275",""},
	{"1276",""},
	{"1277",""},
	{"1278",""},
	{"1279",""},
	{"1280",""},
	{"1281",""},
	{"1282",""},
	{"1283",""},
	{"1284",""},
	{"1285",""},
	{"1286",""},
	{"1287",""},
	{"1288",""},
	{"1289",""},
	{"1290",""},
	{"1291",""},
	{"1292",""},
	{"1293",""},
	{"1294",""},
	{"1295",""},
	{"1296",""},
	{"1297",""},
	{"1298",""},
	{"1299",""},
	{"1300",""},
	{"1301","dense fog (visibility reduced to Q)"},
	{"1302","dense fog. Visibility reduced to <30 m"},
	{"1303","dense fog. Visibility reduced to <50 m"},
	{"1304","fog (visibility reduced to Q)"},
	{"1305","fog. Visibility reduced to <100 m"},
	{"1306",""},
	{"1307","patchy fog (visibility reduced to Q)"},
	{"1308","freezing fog (visibility reduced to Q)"},
	{"1309","smoke hazard (visibility reduced to Q)"},
	{"1310","blowing dust (visibility reduced to Q)"},
	{"1311",""},
	{"1312","snowfall and fog (visibility reduced to Q)"},
	{"1313","visibility improved"},
	{"1314","message cancelled"},
	{"1315",""},
	{"1316",""},
	{"1317",""},
	{"1318","visibility reduced (to Q)"},
	{"1319","visibility reduced to <30 m"},
	{"1320","visibility reduced to <50 m"},
	{"1321","visibility reduced to <100 m"},
	{"1322","white out (visibility reduced to Q)"},
	{"1323","blowing snow (visibility reduced to Q)"},
	{"1324","spray hazard (visibility reduced to Q)"},
	{"1325","low sun glare"},
	{"1326","sandstorms (visibility reduced to Q)"},
	{"1327",""},
	{"1328",""},
	{"1329",""},
	{"1330",""},
	{"1331",""},
	{"1332","smog alert"},
	{"1333",""},
	{"1334",""},
	{"1335",""},
	{"1336",""},
	{"1337","freezing fog (visibility reduced to Q). Slippery roads"},
	{"1338","no motor vehicles due to smog alert"},
	{"1339",""},
	{"1340","swarms of insects (visibility reduced to Q)"},
	{"1341",""},
	{"1342",""},
	{"1343",""},
	{"1344",""},
	{"1345","fog clearing"},
	{"1346","fog forecast withdrawn"},
	{"1347",""},
	{"1348",""},
	{"1349",""},
	{"1350",""},
	{"1351",""},
	{"1352",""},
	{"1353",""},
	{"1354",""},
	{"1355",""},
	{"1356",""},
	{"1357",""},
	{"1358",""},
	{"1359",""},
	{"1360",""},
	{"1361",""},
	{"1362",""},
	{"1363",""},
	{"1364",""},
	{"1365",""},
	{"1366",""},
	{"1367",""},
	{"1368",""},
	{"1369",""},
	{"1370",""},
	{"1371",""},
	{"1372",""},
	{"1373",""},
	{"1374",""},
	{"1375",""},
	{"1376",""},
	{"1377",""},
	{"1378",""},
	{"1379",""},
	{"1380",""},
	{"1381",""},
	{"1382",""},
	{"1383",""},
	{"1384",""},
	{"1385",""},
	{"1386",""},
	{"1387",""},
	{"1388",""},
	{"1389",""},
	{"1390",""},
	{"1391",""},
	{"1392",""},
	{"1393",""},
	{"1394",""},
	{"1395",""},
	{"1396",""},
	{"1397",""},
	{"1398",""},
	{"1399",""},
	{"1400",""},
	{"1401",""},
	{"1402",""},
	{"1403",""},
	{"1404",""},
	{"1405",""},
	{"1406",""},
	{"1407",""},
	{"1408",""},
	{"1409",""},
	{"1410",""},
	{"1411",""},
	{"1412",""},
	{"1413",""},
	{"1414",""},
	{"1415",""},
	{"1416",""},
	{"1417",""},
	{"1418",""},
	{"1419",""},
	{"1420",""},
	{"1421",""},
	{"1422",""},
	{"1423",""},
	{"1424",""},
	{"1425",""},
	{"1426",""},
	{"1427",""},
	{"1428",""},
	{"1429",""},
	{"1430",""},
	{"1431",""},
	{"1432",""},
	{"1433",""},
	{"1434",""},
	{"1435",""},
	{"1436",""},
	{"1437",""},
	{"1438",""},
	{"1439",""},
	{"1440",""},
	{"1441",""},
	{"1442",""},
	{"1443",""},
	{"1444",""},
	{"1445",""},
	{"1446",""},
	{"1447",""},
	{"1448",""},
	{"1449",""},
	{"1450","international sports meeting"},
	{"1451","match"},
	{"1452","tournament"},
	{"1453","athletics meeting"},
	{"1454","ball game"},
	{"1455","boxing tournament"},
	{"1456","bull fight"},
	{"1457","cricket match"},
	{"1458","cycle race"},
	{"1459","football match"},
	{"1460","golf tournament"},
	{"1461","marathon"},
	{"1462","race meeting"},
	{"1463","rugby match"},
	{"1464","show jumping"},
	{"1465","tennis tournament"},
	{"1466","water sports meeting"},
	{"1467","winter sports meeting"},
	{"1468","funfair"},
	{"1469","trade fair"},
	{"1470","procession"},
	{"1471","sightseers obstructing access"},
	{"1472","people on roadway"},
	{"1473","children on roadway"},
	{"1474","cyclists on roadway"},
	{"1475","strike"},
	{"1476","security incident"},
	{"1477","police checkpoint"},
	{"1478","terrorist incident"},
	{"1479","gunfire on roadway, danger"},
	{"1480","civil emergency"},
	{"1481","air raid, danger"},
	{"1482","people on roadway. Danger"},
	{"1483","children on roadway. Danger"},
	{"1484","cyclists on roadway. Danger"},
	{"1485","closed due to security incident"},
	{"1486","security incident. Delays (Q)"},
	{"1487","security incident. Delays (Q) expected"},
	{"1488","security incident. Long delays (Q)"},
	{"1489","police checkpoint. Delays (Q)"},
	{"1490","police checkpoint. Delays (Q) expected"},
	{"1491","police checkpoint. Long delays (Q)"},
	{"1492","security alert withdrawn"},
	{"1493","sports traffic cleared"},
	{"1494","evacuation"},
	{"1495","evacuation. Heavy traffic"},
	{"1496","traffic disruption cleared"},
	{"1497",""},
	{"1498",""},
	{"1499",""},
	{"1500",""},
	{"1501","major event"},
	{"1502","sports event meeting"},
	{"1503","show"},
	{"1504","festival"},
	{"1505","exhibition"},
	{"1506","fair"},
	{"1507","market"},
	{"1508","ceremonial event"},
	{"1509","state occasion"},
	{"1510","parade"},
	{"1511","crowd"},
	{"1512","march"},
	{"1513","demonstration"},
	{"1514","public disturbance"},
	{"1515","security alert"},
	{"1516","bomb alert"},
	{"1517","major event. Stationary traffic"},
	{"1518","major event. Danger of stationary traffic"},
	{"1519","major event. Queuing traffic"},
	{"1520","major event. Danger of queuing traffic"},
	{"1521","major event. Slow traffic"},
	{"1522","major event. Slow traffic expected"},
	{"1523","major event. Heavy traffic"},
	{"1524","major event. Heavy traffic expected"},
	{"1525","major event. Traffic flowing freely"},
	{"1526","major event. Traffic building up"},
	{"1527","closed due to major event"},
	{"1528","major event. Delays (Q)"},
	{"1529","major event. Delays (Q) expected"},
	{"1530","major event. Long delays (Q)"},
	{"1531","sports meeting. Stationary traffic"},
	{"1532","sports meeting. Danger of stationary traffic"},
	{"1533","sports meeting. Queuing traffic"},
	{"1534","sports meeting. Danger of queuing traffic"},
	{"1535","sports meeting. Slow traffic"},
	{"1536","sports meeting. Slow traffic expected"},
	{"1537","sports meeting. Heavy traffic"},
	{"1538","sports meeting. Heavy traffic expected"},
	{"1539","sports meeting. Traffic flowing freely"},
	{"1540","sports meeting. Traffic building up"},
	{"1541","closed due to sports meeting"},
	{"1542","sports meeting. Delays (Q)"},
	{"1543","sports meeting. Delays (Q) expected"},
	{"1544","sports meeting. Long delays (Q)"},
	{"1545","fair. Stationary traffic"},
	{"1546","fair. Danger of stationary traffic"},
	{"1547","fair. Queuing traffic"},
	{"1548","fair. Danger of queuing traffic"},
	{"1549","fair. Slow traffic"},
	{"1550","fair. Slow traffic expected"},
	{"1551","fair. Heavy traffic"},
	{"1552","fair. Heavy traffic expected"},
	{"1553","fair. Traffic flowing freely"},
	{"1554","fair. Traffic building up"},
	{"1555","closed due to fair"},
	{"1556","fair. Delays (Q)"},
	{"1557","fair. Delays (Q) expected"},
	{"1558","fair. Long delays (Q)"},
	{"1559","closed due to parade"},
	{"1560","parade. Delays (Q)"},
	{"1561","parade. Delays (Q) expected"},
	{"1562","parade. Long delays (Q)"},
	{"1563","closed due to strike"},
	{"1564","strike. Delays (Q)"},
	{"1565","strike. Delays (Q) expected"},
	{"1566","strike. Long delays (Q)"},
	{"1567","closed due to demonstration"},
	{"1568","demonstration. Delays (Q)"},
	{"1569","demonstration. Delays (Q) expected"},
	{"1570","demonstration. Long delays (Q)"},
	{"1571","security alert. Stationary traffic"},
	{"1572","security alert. Danger of stationary traffic"},
	{"1573","security alert. Queuing traffic"},
	{"1574","security alert. Danger of queuing traffic"},
	{"1575","security alert. Slow traffic"},
	{"1576","security alert. Slow traffic expected"},
	{"1577","security alert. Heavy traffic"},
	{"1578","security alert. Heavy traffic expected"},
	{"1579","security alert. Traffic building up"},
	{"1580","closed due to security alert"},
	{"1581","security alert. Delays (Q)"},
	{"1582","security alert. Delays (Q) expected"},
	{"1583","security alert. Long delays (Q)"},
	{"1584","traffic has returned to normal"},
	{"1585","message cancelled"},
	{"1586","security alert. Traffic flowing freely"},
	{"1587","air raid warning cancelled"},
	{"1588","civil emergency cancelled"},
	{"1589","message cancelled"},
	{"1590","several major events"},
	{"1591","information about major event no longer valid"},
	{"1592","automobile race"},
	{"1593","baseball game"},
	{"1594","basketball game"},
	{"1595","boat race"},
	{"1596","concert"},
	{"1597","hockey game"},
	{"1598",""},
	{"1599",""},
	{"1600",""},
	{"1601","delays (Q)"},
	{"1602","delays up to 15 minutes"},
	{"1603","delays up to 30 minutes"},
	{"1604","delays up to one hour"},
	{"1605","delays up to two hours"},
	{"1606","delays of several hours"},
	{"1607","delays (Q) expected"},
	{"1608","long delays (Q)"},
	{"1609","delays (Q) for heavy vehicles"},
	{"1610","delays up to 15 minutes for heavy lorr(y/ies)"},
	{"1611","delays up to 30 minutes for heavy lorr(y/ies)"},
	{"1612","delays up to one hour for heavy lorr(y/ies)"},
	{"1613","delays up to two hours for heavy lorr(y/ies)"},
	{"1614","delays of several hours for heavy lorr(y/ies)"},
	{"1615","service suspended (until Q)"},
	{"1616","(Q) service withdrawn"},
	{"1617","(Q) service(s) fully booked"},
	{"1618","(Q) service(s) fully booked for heavy vehicles"},
	{"1619","normal services resumed"},
	{"1620","message cancelled"},
	{"1621","delays up to 5 minutes"},
	{"1622","delays up to 10 minutes"},
	{"1623","delays up to 20 minutes"},
	{"1624","delays up to 25 minutes"},
	{"1625","delays up to 40 minutes"},
	{"1626","delays up to 50 minutes"},
	{"1627","delays up to 90 minutes"},
	{"1628","delays up to three hours"},
	{"1629","delays up to four hours"},
	{"1630","delays up to five hours"},
	{"1631","very long delays (Q)"},
	{"1632","delays of uncertain duration"},
	{"1633","delayed until further notice"},
	{"1634","cancellations"},
	{"1635","park and ride service not operating (until Q)"},
	{"1636","special public transport services operating (until Q)"},
	{"1637","normal services not operating (until Q)"},
	{"1638","rail services not operating (until Q)"},
	{"1639","bus services not operating (until Q)"},
	{"1640","shuttle service operating (until Q)"},
	{"1641","free shuttle service operating (until Q)"},
	{"1642","delays (Q) for heavy lorr(y/ies)"},
	{"1643","delays (Q) for buses"},
	{"1644","(Q) service(s) fully booked for heavy lorr(y/ies)"},
	{"1645","(Q) service(s) fully booked for buses"},
	{"1646","next departure (Q) for heavy lorr(y/ies)"},
	{"1647","next departure (Q) for buses"},
	{"1648","delays cleared"},
	{"1649","rapid transit service not operating (until Q)"},
	{"1650","delays (Q) possible"},
	{"1651","underground service not operating (until Q)"},
	{"1652","cancellations expected"},
	{"1653","long delays expected"},
	{"1654","very long delays expected"},
	{"1655","all services fully booked (until Q)"},
	{"1656","next arrival (Q)"},
	{"1657","rail services irregular. Delays (Q)"},
	{"1658","bus services irregular. Delays (Q)"},
	{"1659","underground services irregular"},
	{"1660","normal public transport services resumed"},
	{"1661","ferry service not operating (until Q)"},
	{"1662","park and ride trip time (Q)"},
	{"1663","delay expected to be cleared"},
	{"1664",""},
	{"1665",""},
	{"1666",""},
	{"1667",""},
	{"1668",""},
	{"1669",""},
	{"1670",""},
	{"1671",""},
	{"1672",""},
	{"1673",""},
	{"1674",""},
	{"1675",""},
	{"1676",""},
	{"1677",""},
	{"1678",""},
	{"1679",""},
	{"1680",""},
	{"1681",""},
	{"1682",""},
	{"1683",""},
	{"1684",""},
	{"1685",""},
	{"1686",""},
	{"1687",""},
	{"1688",""},
	{"1689",""},
	{"1690",""},
	{"1691",""},
	{"1692",""},
	{"1693",""},
	{"1694",""},
	{"1695","current trip time (Q)"},
	{"1696","expected trip time (Q)"},
	{"1697",""},
	{"1698",""},
	{"1699",""},
	{"1700","(Q) slow moving maintenance vehicle(s)"},
	{"1701","(Q) vehicle(s) on wrong carriageway"},
	{"1702","dangerous vehicle warning cleared"},
	{"1703","message cancelled"},
	{"1704","(Q) reckless driver(s)"},
	{"1705","(Q) prohibited vehicle(s) on the roadway"},
	{"1706","(Q) emergency vehicles"},
	{"1707","(Q) high-speed emergency vehicles"},
	{"1708","high-speed chase (involving Q vehicles)"},
	{"1709","spillage occurring from moving vehicle"},
	{"1710","objects falling from moving vehicle"},
	{"1711","emergency vehicle warning cleared"},
	{"1712","road cleared"},
	{"1713",""},
	{"1714",""},
	{"1715",""},
	{"1716",""},
	{"1717",""},
	{"1718",""},
	{"1719",""},
	{"1720","rail services irregular"},
	{"1721","public transport services not operating"},
	{"1722",""},
	{"1723",""},
	{"1724",""},
	{"1725",""},
	{"1726",""},
	{"1727",""},
	{"1728",""},
	{"1729",""},
	{"1730",""},
	{"1731","(Q) abnormal load(s), danger"},
	{"1732","(Q) wide load(s), danger"},
	{"1733","(Q) long load(s), danger"},
	{"1734","(Q) slow vehicle(s), danger"},
	{"1735","(Q) track-laying vehicle(s), danger"},
	{"1736","(Q) vehicle(s) carrying hazardous materials. Danger"},
	{"1737","(Q) convoy(s), danger"},
	{"1738","(Q) military convoy(s), danger"},
	{"1739","(Q) over-height load(s), danger"},
	{"1740","abnormal load causing slow traffic. Delays (Q)"},
	{"1741","convoy causing slow traffic. Delays (Q)"},
	{"1742",""},
	{"1743",""},
	{"1744",""},
	{"1745",""},
	{"1746",""},
	{"1747",""},
	{"1748",""},
	{"1749",""},
	{"1750",""},
	{"1751","(Q) abnormal load(s)"},
	{"1752","(Q) wide load(s)"},
	{"1753","(Q) long load(s)"},
	{"1754","(Q) slow vehicle(s)"},
	{"1755","(Q) convoy(s)"},
	{"1756","abnormal load. Delays (Q)"},
	{"1757","abnormal load. Delays (Q) expected"},
	{"1758","abnormal load. Long delays (Q)"},
	{"1759","convoy causing delays (Q)"},
	{"1760","convoy. Delays (Q) expected"},
	{"1761","convoy causing long delays (Q)"},
	{"1762","exceptional load warning cleared"},
	{"1763","message cancelled"},
	{"1764","(Q) track-laying vehicle(s)"},
	{"1765","(Q) vehicle(s) carrying hazardous materials"},
	{"1766","(Q) military convoy(s)"},
	{"1767","(Q) abnormal load(s). No overtaking"},
	{"1768","Vehicles carrying hazardous materials have to stop at next safe place!"},
	{"1769","hazardous load warning cleared"},
	{"1770","convoy cleared"},
	{"1771","warning cleared"},
	{"1772",""},
	{"1773",""},
	{"1774",""},
	{"1775",""},
	{"1776",""},
	{"1777",""},
	{"1778",""},
	{"1779",""},
	{"1780",""},
	{"1781",""},
	{"1782",""},
	{"1783",""},
	{"1784",""},
	{"1785",""},
	{"1786",""},
	{"1787",""},
	{"1788",""},
	{"1789",""},
	{"1790",""},
	{"1791",""},
	{"1792",""},
	{"1793",""},
	{"1794",""},
	{"1795",""},
	{"1796",""},
	{"1797",""},
	{"1798",""},
	{"1799",""},
	{"1800",""},
	{"1801","lane control signs not working"},
	{"1802","emergency telephones not working"},
	{"1803","emergency telephone number not working"},
	{"1804","(Q sets of) traffic lights not working"},
	{"1805","(Q sets of) traffic lights working incorrectly"},
	{"1806","level crossing failure"},
	{"1807","(Q sets of) traffic lights not working. Stationary traffic"},
	{"1808","(Q sets of) traffic lights not working. Danger of stationary traffic"},
	{"1809","(Q sets of) traffic lights not working. Queuing traffic"},
	{"1810","(Q sets of) traffic lights not working. Danger of queuing traffic"},
	{"1811","(Q sets of) traffic lights not working. Slow traffic"},
	{"1812","(Q sets of) traffic lights not working. Slow traffic expected"},
	{"1813","(Q sets of) traffic lights not working. Heavy traffic"},
	{"1814","(Q sets of) traffic lights not working. Heavy traffic expected"},
	{"1815","(Q sets of) traffic lights not working. Traffic flowing freely"},
	{"1816","(Q sets of) traffic lights not working. Traffic building up"},
	{"1817","traffic lights not working. Delays (Q)"},
	{"1818","traffic lights not working. Delays (Q) expected"},
	{"1819","traffic lights not working. Long delays (Q)"},
	{"1820","level crossing failure. Stationary traffic"},
	{"1821","level crossing failure. Danger of stationary traffic"},
	{"1822","level crossing failure. Queuing traffic"},
	{"1823","level crossing failure. Danger of queuing traffic"},
	{"1824","level crossing failure. Slow traffic"},
	{"1825","level crossing failure. Slow traffic expected"},
	{"1826","level crossing failure. Heavy traffic"},
	{"1827","level crossing failure. Heavy traffic expected"},
	{"1828","level crossing failure. Traffic flowing freely"},
	{"1829","level crossing failure. Traffic building up"},
	{"1830","level crossing failure. Delays (Q)"},
	{"1831","level crossing failure. Delays (Q) expected"},
	{"1832","level crossing failure. Long delays (Q)"},
	{"1833","electronic signs repaired"},
	{"1834","emergency call facilities restored"},
	{"1835","traffic signals repaired"},
	{"1836","level crossing now working normally"},
	{"1837","message cancelled"},
	{"1838","lane control signs working incorrectly"},
	{"1839","lane control signs operating"},
	{"1840","variable message signs not working"},
	{"1841","variable message signs working incorrectly"},
	{"1842","variable message signs operating"},
	{"1843","(Q sets of) ramp control signals not working"},
	{"1844","(Q sets of) ramp control signals working incorrectly"},
	{"1845","(Q sets of) temporary traffic lights not working"},
	{"1846","(Q sets of) temporary traffic lights working incorrectly"},
	{"1847","traffic signal control computer not working"},
	{"1848","traffic signal timings changed"},
	{"1849","tunnel ventilation not working"},
	{"1850","lane control signs not working. Danger"},
	{"1851","temporary width limit (Q)"},
	{"1852","temporary width limit lifted"},
	{"1853",""},
	{"1854","traffic regulations have been changed"},
	{"1855","less than 50 parking spaces available"},
	{"1856","no parking information available (until Q)"},
	{"1857","message cancelled"},
	{"1858","Snowplough. Delays (Q)"},
	{"1859",""},
	{"1860",""},
	{"1861","temporary height limit (Q)"},
	{"1862","temporary height limit lifted"},
	{"1863",""},
	{"1864","lane control signs working incorrectly. Danger"},
	{"1865","emergency telephones out of order. Extra police patrols in operation"},
	{"1866","emergency telephones out of order. In emergency, wait for police patrol"},
	{"1867","(Q sets of) traffic lights not working. Danger"},
	{"1868","traffic lights working incorrectly. Delays (Q)"},
	{"1869","traffic lights working incorrectly. Delays (Q) expected"},
	{"1870","traffic lights working incorrectly. Long delays (Q)"},
	{"1871","temporary axle load limit (Q)"},
	{"1872","temporary gross weight limit (Q)"},
	{"1873","temporary gross weight limit lifted"},
	{"1874","temporary axle weight limit lifted"},
	{"1875","(Q sets of) traffic lights working incorrectly. Danger"},
	{"1876","temporary traffic lights not working. Delays (Q)"},
	{"1877","temporary traffic lights not working. Delays (Q) expected"},
	{"1878","temporary traffic lights not working. Long delays (Q)"},
	{"1879","(Q sets of) temporary traffic lights not working. Danger"},
	{"1880","traffic signal control computer not working. Delays (Q)"},
	{"1881","temporary length limit (Q)"},
	{"1882","temporary length limit lifted"},
	{"1883","message cancelled"},
	{"1884","traffic signal control computer not working. Delays (Q) expected"},
	{"1885","traffic signal control computer not working. Long delays (Q)"},
	{"1886","normal parking restrictions lifted"},
	{"1887","special parking restrictions in force"},
	{"1888","10% full"},
	{"1889","20% full"},
	{"1890","30% full"},
	{"1891","40% full"},
	{"1892","50% full"},
	{"1893","60% full"},
	{"1894","70% full"},
	{"1895","80% full"},
	{"1896","90% full"},
	{"1897","less than 10 parking spaces available"},
	{"1898","less than 20 parking spaces available"},
	{"1899","less than 30 parking spaces available"},
	{"1900","less than 40 parking spaces available"},
	{"1901","next departure (Q)"},
	{"1902","next departure (Q) for heavy vehicles"},
	{"1903","car park (Q) full"},
	{"1904","all car parks (Q) full"},
	{"1905","less than (Q) car parking spaces available"},
	{"1906","park and ride service operating (until Q)"},
	{"1907","(null event) {no event description, but location etc. given in message}"},
	{"1908","switch your car radio (to Q)"},
	{"1909","alarm call: important new information on this frequency follows now in normal programme"},
	{"1910","alarm set: new information will be broadcast between these times in normal programme"},
	{"1911","message cancelled"},
	{"1912",""},
	{"1913","switch your car radio (to Q)"},
	{"1914","no information available (until Q)"},
	{"1915","this message is for test purposes only (number Q), please ignore"},
	{"1916","no information available (until Q) due to technical problems"},
	{"1917",""},
	{"1918","full"},
	{"1919",""},
	{"1920","only a few parking spaces available"},
	{"1921","(Q) parking spaces available"},
	{"1922","expect car park to be full"},
	{"1923","expect no parking spaces available"},
	{"1924","multi story car parks full"},
	{"1925","no problems to report with park and ride services"},
	{"1926","no parking spaces available"},
	{"1927","no parking (until Q)"},
	{"1928","special parking restrictions lifted"},
	{"1929","urgent information will be given (at Q) on normal programme broadcasts"},
	{"1930","this TMC-service is not active (until Q)"},
	{"1931","detailed information will be given (at Q) on normal programme broadcasts"},
	{"1932","detailed information is provided by another TMC service"},
	{"1933",""},
	{"1934","no park and ride information available (until Q)"},
	{"1935",""},
	{"1936",""},
	{"1937",""},
	{"1938","park and ride information service resumed"},
	{"1939",""},
	{"1940","additional regional information is provided by another TMC service"},
	{"1941","additional local information is provided by another TMC service"},
	{"1942","additional public transport information is provided by another TMC service"},
	{"1943","national traffic information is provided by another TMC service"},
	{"1944","this service provides major road information"},
	{"1945","this service provides regional travel information"},
	{"1946","this service provides local travel information"},
	{"1947","no detailed regional information provided by this service"},
	{"1948","no detailed local information provided by this service"},
	{"1949","no cross-border information provided by this service"},
	{"1950","information restricted to this area"},
	{"1951","no new traffic information available (until Q)"},
	{"1952","no public transport information available"},
	{"1953","this TMC-service is being suspended (at Q)"},
	{"1954","active TMC-service will resume (at Q)"},
	{"1955","reference to audio programmes no longer valid"},
	{"1956","reference to other TMC services no longer valid"},
	{"1957","previous announcement about this or other TMC services no longer valid"},
	{"1958",""},
	{"1959",""},
	{"1960",""},
	{"1961","allow emergency vehicles to pass in the carpool lane"},
	{"1962","carpool lane available for all vehicles"},
	{"1963","police directing traffic via the carpool lane"},
	{"1964","rail Information service not available"},
	{"1965","rail information service resumed"},
	{"1966","rapid transit information service not available"},
	{"1967","rapid transit information service resumed"},
	{"1968",""},
	{"1969",""},
	{"1970",""},
	{"1971","police directing traffic"},
	{"1972","bus lane available for all vehicles"},
	{"1973","police directing traffic via the bus-lane"},
	{"1974","allow emergency vehicles to pass"},
	{"1975",""},
	{"1976",""},
	{"1977","allow emergency vehicles to pass in the heavy vehicle lane"},
	{"1978","heavy vehicle lane available for all vehicles"},
	{"1979","police directing traffic via the heavy vehicle lane"},
	{"1980",""},
	{"1981",""},
	{"1982","bus lane closed"},
	{"1983","power failure"},
	{"1984",""},
	{"1985",""},
	{"1986",""},
	{"1987",""},
	{"1988",""},
	{"1989",""},
	{"1990",""},
	{"1991",""},
	{"1992",""},
	{"1993",""},
	{"1994",""},
	{"1995",""},
	{"1996",""},
	{"1997",""},
	{"1998",""},
	{"1999",""},
	{"2000","closed due to smog alert (until Q)"},
	{"2001",""},
	{"2002",""},
	{"2003",""},
	{"2004",""},
	{"2005",""},
	{"2006","closed for vehicles with less than three occupants {not valid for lorries}"},
	{"2007","closed for vehicles with only one occupant {not valid for lorries}"},
	{"2008",""},
	{"2009",""},
	{"2010",""},
	{"2011",""},
	{"2012",""},
	{"2013","service area busy"},
	{"2014",""},
	{"2015",""},
	{"2016",""},
	{"2017",""},
	{"2018",""},
	{"2019",""},
	{"2020",""},
	{"2021","service not operating, substitute service available"},
	{"2022","public transport strike"},
	{"2023",""},
	{"2024",""},
	{"2025",""},
	{"2026",""},
	{"2027",""},
	{"2028","message cancelled"},
	{"2029","message cancelled"},
	{"2030","message cancelled"},
	{"2031",""},
	{"2032",""},
	{"2033","message cancelled"},
	{"2034","message cancelled"},
	{"2035","message cancelled"},
	{"2036",""},
	{"2037",""},
	{"2038","message cancelled"},
	{"2039","message cancelled"},
	{"2040","message cancelled"},
	{"2041","nothing to report"},
	{"2042",""},
	{"2043",""},
	{"2044",""},
	{"2045",""},
	{"2046",""},
	{"2047","(null message) {completely silent message, see EN ISO 14819-1, 3.5.4}"}};
